In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd
import glob
import os
from IPython.display import display
import matplotlib.pyplot as plt
import json
from sklearn import preprocessing
from keras.models import Model
from keras.layers import Input, LSTM, Dense, Embedding
from keras.preprocessing.text import Tokenizer
import tensorflow_addons as tfa
import decimal
from sklearn.preprocessing import normalize
from sklearn.preprocessing import MinMaxScaler
import math
from tensorflow.keras import activations
import itertools

In [2]:
trailers_csv = "/Volumes/Seagate/natasha-diploma/trailers.csv"
trailers_df = pd.read_csv(trailers_csv, index_col=None, header=0)
trailers_df.drop(trailers_df.columns[trailers_df.columns.str.contains('Unnamed',case = False)],axis = 1, inplace = True)
display(trailers_df.head())

duration release_date  restrict                 orig_title  kinopoisk_id  \
0    5816.0   2019-04-05      18.0                       Phil        960568   
1    5123.0   2019-04-02      18.0                Tooth Fairy       1126022   
2    4667.0   2019-01-19      16.0                    Wake Up       1069713   
3    6148.0   2019-08-09      16.0                The Kitchen       1117988   
4    6013.0   2019-05-02      12.0  Pokémon Detective Pikachu        994864   

   imdb_rating  kinopoisk_rating  \
0          5.4              5.86   
1          2.2              0.00   
2          2.9              0.00   
3          5.5              5.50   
4          6.6              6.56   

                                            synopsis          categories  \
0  Фил – стоматолог, страдающий от депрессии. Его...            {Фильмы}   
1  Старая женщина начинает рассказывать легенду о...            {Фильмы}   
2  Врач-психиатр исследует дневник девушки, котор...            {Фильмы}   
3  Смотрите в 4К! Три жены ирландских гангстеров,...            {Фильмы}   
4  Смотрите в 4K! Элитный детектив Пикачу отправл...  {Для детей,Фильмы}   

                                              genres  ...  \
0                         {Драмы,Зарубежные,Комедии}  ...   
1                        {Зарубежные,Триллеры,Ужасы}  ...   
2       {Боевики,Зарубежные,Криминал,Триллеры,Ужасы}  ...   
3    {Боевики,Драмы,Зарубежные,Криминал,По комиксам}  ...   
4  {Детективы,Зарубежные,Комедии,Семейные,Фильмы,...  ...   

                                            emotions  \
0  {'neutral': 0.5312193632125854, 'negative': 0....   
1  {'negative': 0.4688006341457367, 'skip': 0.392...   
2  {'positive': 0.3140605390071869, 'negative': 0...   
3  {'neutral': 0.4765896201133728, 'negative': 0....   
4  {'neutral': 0.4532718360424042, 'negative': 0....   

                                      Place of act  \
0                                          ['США']   
1                                ['не определено']   
2                                ['не определено']   
3                         ['большой город', 'США']   
4  ['вымышленная страна (город)', 'большой город']   

                                           Qualities  \
0                                       ['дебютный']   
1     ['зрелищные', 'жанровый', 'неожиданный финал']   
2                           ['жанровый', 'дебютный']   
3                      ['жанровый', 'остросюжетные']   
4  ['частично анимационный', 'зрелищные', 'кассов...   

                      Time of act  \
0  ['21-й век', 'новейшее время']   
1               ['не определено']   
2              ['новейшее время']   
3                    ['20-й век']   
4                    ['21-й век']   

                                       Based on  \
0                    ['оригинального сценария']   
1  ['эпоса и легенд', 'оригинального сценария']   
2                    ['оригинального сценария']   
3                                  ['комиксов']   
4        ['оригинального сценария', 'сериалов']   

                                            Audience  \
0                   ['для молодёжи', 'для взрослых']   
1  ['для взрослых', 'для мужчин', 'для подготовле...   
2  ['для взрослых', 'для подготовленного зрителя'...   
3       ['для мужчин', 'для женщин', 'для взрослых']   
4  ['для детей 13-16 лет', '9 лет', '8 лет', '7-1...   

                                                Mood  \
0       ['грустный', 'депрессивный', 'трогательный']   
1  ['трагичные', 'мрачные', 'шокирующие', 'захват...   
2  ['захватывающие', 'жестокие', 'напряженные', '...   
3  ['захватывающие', 'авантюрный', 'жестокие', 'н...   
4  ['авантюрный', 'захватывающие', 'динамичный', ...   

                                            Subgenre  \
0                            ['Драмы', 'Комедийные']   
1                               ['ужасы', 'триллер']   
2                    ['Драмы', 'Боевики', 'триллер']   
3               ['Боевики', 'Драмы', 'криминальные']   
4  [

In [3]:
sessions_csv = "/Volumes/Seagate/natasha-diploma/sessions.csv"
sessions_df = pd.read_csv(sessions_csv, index_col=None, header=0)
sessions_df.drop(sessions_df.columns[sessions_df.columns.str.contains('Unnamed',case = False)],axis = 1, inplace = True)
display(sessions_df)

0                               1  \
0    403a42b604f504069c41d39c5a4fc2  23ee5640ec588ffaa78afa3268b04a   
1    a5b2dd3ed41aabb5733c7cfffff0bc  25e573b81ab69d6cf700a51281fc2a   
2    80870ec50515107ba7034ab758cebe  cd522afebcf91625c3cd811f3fb6e2   
3    d66440e7524c0a8b9b206fbb7295ba  046f93c91d0befd4625f00e07eb473   
4    231b80c884b2f1390e17f09a187889  bd6707bb04cfb8880a5f783c85be20   
..                              ...                             ...   
196  91e8db1b91acc7bf903bf670461db3  f65c8906c07b627a760a0671de7144   
197  c718bcdf6240802ba7123a7a631199  5e62a64d4f0d6ca3fce397267bf9f3   
198  ee78a3aae1a69f2e4b82f26d41d594  11fe2dd4cccaf0567c878e19e1811a   
199  b0b062dc25c4dada316183941b100c  80870ec50515107ba7034ab758cebe   
200  02a7f8e9b88ca2a74c6637332b0998  c06fea4a59b3cc8a188a7a83bb2f61   

                                  2                               3  \
0    5b150a1cae009459493bd0fe5c7b3e  e291f8ae1de4a38c71027e9c91d51c   
1    49c58f679f72e0f02b97bdeee1a1bb  c0be492c14bcec5ab3dfd34d95d6f5   
2    061a59839837a123a916a70947f075  07e873c5aac8ffaf97897fbd0dfbf6   
3    199cf6d89a2f06fc552ebf86105d7d  2adfc14bbc0fba5b5d616d6fcfe3de   
4    bbd5df907c099d2cc2b5285b08038e  514f3ee1f00df05dc3900251972245   
..                              ...                             ...   
196  26ba677f7ff11ac529f5f69c54cb0b  be6360babdb2e5910c5bc6f4f04f0d   
197  c5d40f1adeb446df77e65815da405d  bbf4b4a3db602ab9b88845114f7244   
198  aab18e84a97780bafb188fd33cb2a9  838cb9d91dd080147bcc18982bcdbb   
199  d49c4a9b748b9c7abb9d98cdecebef  67c38de267396951227897efc503e1   
200  d579d54561bf36f67f4d1dea329f1d  5ccf8f0bf03df5bf674c2aa36e7fe6   

                                  4                               5  \
0    34cfd44ad5cc2d63441ebf437eccb5  02fbcf93a730c9c9d5e65aef41c67e   
1    b2274b9b4c8c4dc2f79d417ddd71e5  7fd08607f52b89a753437eee177e32   
2    60fb638ff7ab469be8637111fdc837  d49c4a9b748b9c7abb9d98cdecebef   
3    a458a5a362af9a7774780eb4e25365  88bbc5912f946b1fb77fdeaa3f5d4a   
4    961c336b0c2fa04c883c639dfee1ba  d6159553e41857fe23df9d3e746284   
..                              ...                             ...   
196  705c23ed5ae1bc8824fc955b82094b  74733260a8a5143b2eb20c4a62940a   
197  0f462e6bbd719e012902d8814d0e35  e5bca888fec7f8c0116db0002a7077   
198  972821d03656142f33707487f51b66  d6d45793f5b093e8bdf3d8ae4952b6   
199  7b457a5d30f3cb01b6998390ec7abf  67f32aff5488778cb4bbb6b21acc7d   
200  31f08ef4a727a8943644261454f1fa  b5cace1f414bee46d0441934d18bf9   

                                  6                               7  \
0    26b3f811a6b9ed75d3cc5198105fa4  6fcff414343456465369b05f6851eb   
1    25d41576f3529994c878a5d15f6dc7  ece16e15b2286f8287e8935f12b6c2   
2    b0b062dc25c4dada316183941b100c  c7f809aab571e9acdf799a78c5ef61   
3    6d0bb6959972ac92c10d7445982a94  274869b912b256df69b9e7c5c0cb11   
4    d2cd45a49d53702df403cffddd53e6  c0314a446fbef65ce9626b037a70da   
..                              ...                             ...   
196  afed0e34e5af6958fef610a0ac5565  0a49f9b4576a63be41cb96908eba5e   
197  8a2483e11828332a9e2fc8659ae38f  bb59c82aeb5e44eb5735d5a1c016b8   
198  28731720ee3330b7107cec47168b8c  dad45a9302ad916f6901b86a744cdd   
199  3d558c3e37ccb70937b171aeb67bbb  97474799458a67e30a70f66407420b   
200  16eb6fb9aee97cb7f6cd83a4ec5608  4d9b46f08e9c1fcf08ecbc5c714098   

                                  8                               9  
0    e2f15819192cded77ed1825a129c0c  41b772a5b18bc724562bfb60f4f3ac  
1    806c0ed32e135afb8db4f3aad71acf  f10b4adf1c732b6b260791fb24f430  
2    67c38de267396951227897efc503e1  7b457a5d30f3cb01b6998390ec7abf  
3    2c5bf20534b80ee47bed9a90b405a0  f456635bb3d2567a3a61133fa9dd89  
4    d6e8f6d21631149a90ac940d3ee227  e762f208419b7449c0731037262bb3  
..                              ...                             ...  
196  baec94926106f54090568b653e84b4  8a2b5f96cc30660b28636fbe2664d5  
197  8d3877a1b26b10642d125ec4fc4c9b  ae90166aa81ab2bf878dace61

In [4]:
movies_id = sessions_df.to_numpy()
movies_id = np.array(movies_id).flatten()
vocab = np.unique(movies_id)
vocab_len = len(vocab)

# print(vocab)
print(vocab_len)
print(movies_id.shape)

366
(2010,)


In [5]:
def getVideoInfo(info_df):
    return [
        np.mean(info_df['temperature'].to_numpy()),
        np.mean(info_df['brightness'].to_numpy()),
        np.mean(info_df['colorfulness'].to_numpy()),
        np.mean(info_df['energy'].to_numpy()),
        np.mean(info_df['tempo'].to_numpy()),
        np.mean(info_df['amplitude'].to_numpy()),
        np.mean(info_df['spectral_rolloff'].to_numpy()),
        np.mean(info_df['mfcc'].to_numpy())
    ]

In [6]:
info = {}
scenes_array = []
del_array_name = []
info_folder = "/Volumes/Seagate/natasha-diploma/videoinfo"
for i in range(0, len(movies_id)):
    try:
        info_csv = info_folder + '/' + movies_id[i] + '.csv'
        info_df =  pd.read_csv(info_csv, index_col=None, header=0)
        info[movies_id[i]] = getVideoInfo(info_df.iloc[: , 4:])
        scenes_array.append(info[movies_id[i]])
    except:
        del_array_name.append(movies_id[i])

In [7]:
def vocab_creater(arr):
    word2idx = {}
    idx2word = {}
    for i in range(len(arr)):
        word2idx[arr[i]] = i
        idx2word[i] = arr[i]

    return word2idx, idx2word, len(arr)

In [8]:
word2idx, idx2word, _ = vocab_creater(vocab)

In [9]:
def toArray(smth):
    new = []
    
    for i in range(len(smth)):
        new.append(word2idx[smth[i]])
    
    return new


tokenized = toArray(movies_id)

In [10]:
print(np.array(scenes_array).shape)
print(np.array(tokenized).shape)

scenes_array = np.nan_to_num(scenes_array, copy=False, nan=0.0, posinf=0.0, neginf=0.0)
scenes_array = normalize(scenes_array, axis=1, norm='l1')

scaler = MinMaxScaler((-1, 1))
scenes_array = np.around(scaler.fit_transform(scenes_array), 3)

print(scenes_array)

(2010, 8)
(2010,)
[[ 1.    -1.    -1.    ...  1.    -1.     0.633]
 [-1.     0.455 -0.021 ...  0.25   0.957  0.364]
 [ 1.    -1.    -1.    ...  1.    -1.     0.633]
 ...
 [-1.     0.375 -0.405 ...  0.184  0.98  -0.463]
 [ 1.    -1.    -1.    ...  1.    -1.     0.633]
 [ 1.    -1.    -1.    ...  1.    -1.     0.633]]


In [11]:
id_size = 1
id_embed_size = 8
vocab_size = 366
embedding_dim = 1024
rnn_units = 1024

In [12]:
class MyModel(tf.keras.Model):
    def __init__(self, vocab_size, id_size, id_embed_size, embedding_dim, rnn_units):
        super().__init__(self)
        self.id_embedding = tf.keras.layers.Embedding(vocab_size, id_embed_size)
        self.normalization = tf.keras.layers.BatchNormalization()
        self.concat = tf.keras.layers.Concatenate()
        self.gru = tf.keras.layers.GRU(rnn_units,
                                       return_sequences=True,
                                       return_state=True)
        self.dense = tf.keras.layers.Dense(vocab_size, activation=activations.relu)

    def call(self, _input, states=None, return_state=False, training=False):
        ids = self.id_embedding(_input[0])
        features = self.normalization(_input[1])
        x = self.concat([ids, features])
        if states is None:
            states = self.gru.get_initial_state(x)
        x, states = self.gru(x, initial_state=states, training=training)
        x = self.dense(x, training=training)

        if return_state:
            return x, states
        else:
            return x
        
#     def train_step(self, data):
#         with tf.GradientTape() as tape:
#             y_pred = self(data, training=True)
#             loss = self.compiled_loss(y, y_pred, regularization_losses=self.losses)

#         trainable_vars = self.trainable_variables
#         gradients = tape.gradient(loss, trainable_vars)
#         self.optimizer.apply_gradients(zip(gradients, trainable_vars))
#         self.compiled_metrics.update_state(y, y_pred)

#         return {m.name: m.result() for m in self.metrics}

In [13]:
train_tokenized = tokenized[:1400]
test_tokenized = tokenized[1400:2000]

train_scenes = scenes_array[:1400]
test_scenes = scenes_array[1400:2000]

ids_ds = tf.data.Dataset.from_tensor_slices(train_tokenized)
features_ds = tf.data.Dataset.from_tensor_slices(train_scenes)

ids_ds_test = tf.data.Dataset.from_tensor_slices(test_tokenized)
features_ds_test = tf.data.Dataset.from_tensor_slices(test_scenes)

ds_test = tf.data.Dataset.zip((ids_ds_test, features_ds_test))

ds = tf.data.Dataset.zip((ids_ds, features_ds))
seq_length = 10
examples_per_epoch = len(tokenized) // (seq_length + 1)

sequences = ds.batch(seq_length + 1, drop_remainder=True)
ids_seq = ids_ds.batch(seq_length + 1, drop_remainder=True)
features_seq = features_ds.batch(seq_length + 1, drop_remainder=True)
sequences_test = ds_test.batch(seq_length + 1, drop_remainder=True)

ds

<ZipDataset shapes: ((), (8,)), types: (tf.int32, tf.float64)>

In [14]:
def full_split_input_target(id_sequence, feature_sequence):
    input_text = (id_sequence[:-1], feature_sequence[:-1])
    target_text = (id_sequence[1:])
    return input_text, target_text

def split_input_target(seq):
    input_text = seq[:-1]
    target_text = seq[1:]
    return input_text, target_text

ds = sequences.map(full_split_input_target)
ids_ds = ids_seq.map(split_input_target)
features_ds = features_seq.map(split_input_target)
ds_test = sequences_test.map(full_split_input_target)

BATCH_SIZE = 32
BUFFER_SIZE = 10000

ds = (
    ds
    .shuffle(BUFFER_SIZE)
    .batch(BATCH_SIZE, drop_remainder=True)
    .prefetch(tf.data.experimental.AUTOTUNE))


ids_ds = (
    ids_ds
    .shuffle(BUFFER_SIZE)
    .batch(BATCH_SIZE, drop_remainder=True)
    .prefetch(tf.data.experimental.AUTOTUNE))

features_ds = (
    features_ds
    .shuffle(BUFFER_SIZE)
    .batch(BATCH_SIZE, drop_remainder=True)
    .prefetch(tf.data.experimental.AUTOTUNE)
)

for _input, _output in ds_test.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True).take(1):
    print(_input)

ds_test = (
    ds_test
    .shuffle(BUFFER_SIZE)
    .batch(BATCH_SIZE, drop_remainder=True)
    .prefetch(tf.data.experimental.AUTOTUNE))

ds

(<tf.Tensor: shape=(32, 10), dtype=int32, numpy=
array([[357, 141, 332,  90,   8,  64, 166,  33, 179,  19],
       [365, 313,  41, 331,  26,  10, 109, 166,  61,  86],
       [ 53, 104,  60, 141, 332, 272, 274, 228,  99, 162],
       [ 60, 130, 284, 240,  28,  89,  40, 134, 173, 128],
       [355,  65, 286, 169, 176, 257,  23, 276, 206, 296],
       [154, 290,   7, 315, 145,  88, 269,  43, 127, 205],
       [231,  53, 104,  60, 141, 332,  90, 354, 201,  76],
       [267, 165, 224, 223, 327, 119, 156, 236, 235, 101],
       [108, 347, 262,  60, 104, 298, 159, 231, 364, 222],
       [141, 332,  90, 299, 192, 259, 161, 312,  85, 196],
       [285, 279, 132, 225, 317, 310, 289, 320, 311,  96],
       [159,  60, 141, 117,  67,  22,  44,  77, 325, 253],
       [258, 271, 213, 143, 182, 156, 223, 224, 165, 119],
       [194, 227, 319,  70, 324, 157, 118, 259, 192, 312],
       [294, 280,  29, 338, 205, 277, 212, 254, 349,  35],
       [ 38, 344, 125, 222,  58, 318, 188, 364, 126,  32],
       

<PrefetchDataset shapes: (((32, 10), (32, 10, 8)), (32, 10)), types: ((tf.int32, tf.float64), tf.int32)>

In [15]:
for _input, _output in ds_test.take(1):
    print(_input, _output)

(<tf.Tensor: shape=(32, 10), dtype=int32, numpy=
array([[294, 280,  29, 338, 205, 277, 212, 254, 349,  35],
       [231,  53, 104,  60, 141, 332,  90, 354, 201,  76],
       [251,  15, 142, 285, 283, 279,  59, 225, 132, 317],
       [147, 164,  45,  58,  57,  97, 199,   9, 201, 242],
       [206, 330, 229, 314,  94, 274, 222,  27, 104, 159],
       [335, 332, 141,  90,   8,  64, 166, 333, 108, 347],
       [ 85, 312, 196, 259, 184, 161, 181, 162, 299, 192],
       [ 60, 130, 284, 240,  28,  89,  40, 134, 173, 128],
       [ 64, 166, 333,  10, 365, 331, 313,  41, 186, 275],
       [141, 332,  90, 299, 192, 259, 161, 312,  85, 196],
       [357, 141, 332,  90,   8,  64, 166,  33, 179,  19],
       [175, 342, 110, 254, 338, 205,  63, 243, 121, 291],
       [ 24,  92, 180,   1, 195, 256, 135,  47, 318,  26],
       [110, 338, 205, 277, 114, 120, 307, 123, 142, 101],
       [365, 313,  41, 331,  26,  10, 109, 166,  61,  86],
       [225, 317, 310, 289, 320,  48, 265, 270, 175, 342],
       

In [16]:
features_ds

<PrefetchDataset shapes: ((32, 10, 8), (32, 10, 8)), types: (tf.float64, tf.float64)>

In [17]:
model = MyModel(
    vocab_size=vocab_size,
    id_size=id_size,
    id_embed_size=id_embed_size,
    embedding_dim=embedding_dim,
    rnn_units=rnn_units)


In [18]:
for _input, _output in ds.take(1):
    example_batch_predictions = model(_input)
    print(example_batch_predictions.shape, "# (batch_size, sequence_length, vocab_size)")
    sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
    sampled_indices = tf.squeeze(sampled_indices, axis=-1).numpy()

    print(sampled_indices)

(32, 10, 366) # (batch_size, sequence_length, vocab_size)
[  6 278  73 290 330 341 274 281  50 284]


In [19]:
tf.config.run_functions_eagerly(True)
model.summary()

Model: "my_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        multiple                  2928      
_________________________________________________________________
batch_normalization (BatchNo multiple                  32        
_________________________________________________________________
concatenate (Concatenate)    multiple                  0         
_________________________________________________________________
gru (GRU)                    multiple                  3201024   
_________________________________________________________________
dense (Dense)                multiple                  375150    
Total params: 3,579,134
Trainable params: 3,579,118
Non-trainable params: 16
_________________________________________________________________


In [20]:
loss = tf.losses.SparseCategoricalCrossentropy(from_logits=True)

In [21]:
model.compile(optimizer='adam', loss=loss, metrics=['accuracy'])

In [22]:
EPOCHS = 200
history = model.fit(ds_test, epochs=EPOCHS)

Epoch 1/200
1/1 [==============================] - 0s 249ms/step - loss: 5.9030 - accuracy: 0.0000e+00
Epoch 2/200
1/1 [==============================] - 0s 237ms/step - loss: 5.8727 - accuracy: 0.0344
Epoch 3/200
1/1 [==============================] - 0s 238ms/step - loss: 5.8597 - accuracy: 0.0250
Epoch 4/200
1/1 [==============================] - 0s 246ms/step - loss: 5.8182 - accuracy: 0.0562
Epoch 5/200
1/1 [==============================] - 0s 240ms/step - loss: 5.7771 - accuracy: 0.0688
Epoch 6/200
1/1 [==============================] - 0s 240ms/step - loss: 5.7392 - accuracy: 0.0625
Epoch 7/200
1/1 [==============================] - 0s 230ms/step - loss: 5.7107 - accuracy: 0.0594
Epoch 8/200
1/1 [==============================] - 0s 232ms/step - loss: 5.6168 - accuracy: 0.0625
Epoch 9/200
1/1 [==============================] - 0s 249ms/step - loss: 5.5483 - accuracy: 0.0437
Epoch 10/200
1/1 [==============================] - 0s 229ms/step - loss: 5.4308 - accuracy: 0.0406
Epoch

Epoch 83/200
1/1 [==============================] - 0s 204ms/step - loss: 1.5844 - accuracy: 0.7437
Epoch 84/200
1/1 [==============================] - 0s 211ms/step - loss: 1.5953 - accuracy: 0.7281
Epoch 85/200
1/1 [==============================] - 0s 243ms/step - loss: 1.3568 - accuracy: 0.7875
Epoch 86/200
1/1 [==============================] - 0s 238ms/step - loss: 1.4350 - accuracy: 0.7531
Epoch 87/200
1/1 [==============================] - 0s 220ms/step - loss: 1.4167 - accuracy: 0.7656
Epoch 88/200
1/1 [==============================] - 0s 207ms/step - loss: 1.5623 - accuracy: 0.7406
Epoch 89/200
1/1 [==============================] - 0s 229ms/step - loss: 1.7340 - accuracy: 0.7344
Epoch 90/200
1/1 [==============================] - 0s 228ms/step - loss: 1.6199 - accuracy: 0.7406
Epoch 91/200
1/1 [==============================] - 0s 219ms/step - loss: 1.5299 - accuracy: 0.7344
Epoch 92/200
1/1 [==============================] - 0s 213ms/step - loss: 1.6204 - accuracy: 0.7281


1/1 [==============================] - 0s 208ms/step - loss: 0.8798 - accuracy: 0.8375
Epoch 165/200
1/1 [==============================] - 0s 207ms/step - loss: 0.9877 - accuracy: 0.8313
Epoch 166/200
1/1 [==============================] - 0s 201ms/step - loss: 1.1258 - accuracy: 0.7969
Epoch 167/200
1/1 [==============================] - 0s 204ms/step - loss: 0.9497 - accuracy: 0.8250
Epoch 168/200
1/1 [==============================] - 0s 203ms/step - loss: 1.0154 - accuracy: 0.8250
Epoch 169/200
1/1 [==============================] - 0s 202ms/step - loss: 1.0659 - accuracy: 0.8031
Epoch 170/200
1/1 [==============================] - 0s 202ms/step - loss: 0.9637 - accuracy: 0.8344
Epoch 171/200
1/1 [==============================] - 0s 208ms/step - loss: 1.0923 - accuracy: 0.8094
Epoch 172/200
1/1 [==============================] - 0s 202ms/step - loss: 0.9422 - accuracy: 0.8406
Epoch 173/200
1/1 [==============================] - 0s 208ms/step - loss: 1.0339 - accuracy: 0.8188
Epoc

In [23]:
ds_test

<PrefetchDataset shapes: (((32, 10), (32, 10, 8)), (32, 10)), types: ((tf.int32, tf.float64), tf.int32)>

In [24]:
model.evaluate(ds_test, batch_size=64, return_dict=True)

1/1 [==============================] - 0s 89ms/step - loss: 0.9076 - accuracy: 0.8500


{'loss': 0.9075837135314941, 'accuracy': 0.8500000238418579}